master:
  runAsUser: 1000
  fsGroup: 1000
  installPlugins:
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - google-oauth-plugin:latest
    - google-source-plugin:latest
    - google-kubernetes-engine:latest
    - google-storage-plugin:latest
#   - job-dsl-plugin:latest
  resources:
    requests:
      cpu: "50m"
      memory: "1024Mi"
    limits:
      cpu: "1"
      memory: "3500Mi"
  javaOpts: "-Xms3500m -Xmx3500m -Djenkins.install.runSetupWizard=false"
  serviceType: ClusterIP
agent:
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
persistence:
  size: 100Gi
serviceAccount:
  name: cd-jenkins

nginx-ingress:
    Enabled: false

OperationsCenter:
    HostName: "${jenkins_hostname}"
    Ingress:
      tls:
      ## Set this to true in order to enable TLS on the ingress record
        Enable: false
        SecretName: core-example-com-tls
        Host: jenkins.cluster.local
